### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by samnoonabrar** [samnoon1971/Surjo#1]
* Add User guide

**Comment by bgcodehub** [comment]
@samnoon1971 I would like to assign this issue to myself. I will start working on it. Thank you!

**Comment by samnoonabrar** [comment]
@bgcodehub Assigned. Thanks!

**Comment by samnoonabrar** [comment]
PR Merged, closing issue. Thanks, @bgcodehub for your contribution.
